# Generated by Django 5.1.5 on 2025-03-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=150)),
                ('quantity', models.PositiveBigIntegerField()),
                ('units', models.CharField(choices=[('liters', 'Liters'), ('kilograms', 'Kilograms'), ('servings', 'servings'), ('pieces', 'pieces')], default='Servings', max_length=150)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('claim', 'claim'), ('claimed', 'Claimed')], default='Claim', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
