# Generated by Django 5.1.5 on 2025-03-31 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='expiration_datetime',
        ),
        migrations.AddField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiration_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
