# Generated by Django 5.1.5 on 2025-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_donation_expiration_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='units',
            field=models.CharField(choices=[('liters', 'Liters'), ('kilograms', 'Kilograms'), ('servings', 'servings'), ('pieces', 'pieces')], max_length=150),
        ),
    ]
