# Generated by Django 5.1.5 on 2025-03-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_donation_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='units',
            field=models.CharField(choices=[('liters', 'Liters'), ('kilograms', 'Kilograms'), ('servings', 'servings'), ('pieces', 'pieces')], default='Servings', max_length=150),
        ),
    ]
