# Generated by Django 5.1.5 on 2025-04-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_customuser_area_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
    ]
