# Generated by Django 5.1.5 on 2025-04-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_useraddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='pincode',
            new_name='pin_code',
        ),
    ]
