# Generated by Django 5.1.5 on 2025-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_pincode_useraddress_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=255)),
            ],
        ),
    ]
