# Generated by Django 5.1.5 on 2025-05-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_locationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('claim', 'claim'), ('claimed', 'Claimed')], default='claim', max_length=150),
        ),
    ]
