# Generated by Django 5.1.5 on 2025-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('claim', 'Claim'), ('claimed', 'Claimed')], default='claim', max_length=150),
        ),
    ]
