# Generated by Django 5.1.5 on 2025-05-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
