# Generated by Django 5.1.5 on 2025-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_donation_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
