# Generated by Django 5.1.5 on 2025-06-12 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_delete_locationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='units',
            field=models.CharField(choices=[('liters', 'Liters'), ('kilograms', 'Kilograms'), ('servings', 'Servings'), ('pieces', 'Pieces')], default='Servings', max_length=150),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN', regex='^\\d{6}$')]),
        ),
    ]
