# Generated by Django 5.1.5 on 2025-03-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
